fix: Capture mmdc error message as string
When rendering to SVG with faulty Mermaid code, I get an error message
with a binary string (with `b'...\n`), which is hard to read for end
users. Capture the error message as string before it ends up in the
`MermaidError` exception. Now the exception contains a string and looks
much nicer.

```
Mermaid exited with error:
[stderr]

Error: Packet block 294 - 296 is not contiguous. It should start from 441.
    at populate (file://...mermaid-11.15.0.js:156484:19)
    at Object.parse (file://...mermaid-11.15.0.js:156553:11)
    at async Diagram.fromText (file://...mermaid-11.15.0.js:177444:7)
    at async Object.render (file://...mermaid-11.15.0.js:177807:14)

[stdout]
Generating single mermaid chart
```

Added a test to check that behavior.